# Experiment Specific
experiment_name: 'UNet_Abdomen_CT_Seg_TEST_MR'
data_root: '/users/scratch/baryaacovi-2024-06-01/projects/datasets/proto/prod'
save_root: '/users/scratch/baryaacovi-2024-06-01/projects/MICCAI23-ProtoContra-SFDA'
source_sites:
- 'CT'
eval_sites:
- 'MR'
resume_dir: '/users/scratch/baryaacovi-2024-06-01/projects/MICCAI23-ProtoContra-SFDA/res/UNet_Abdomen_MR_Seg/exp_27_time_2024-05-04 00:55:07'
# resume: '/users/scratch/baryaacovi-2024-06-01/projects/MICCAI23-ProtoContra-SFDA/res/UNet_Abdomen_CT_Seg/exp_44_time_2024-05-06 14:41:53/saved_models/best_model_epoch_83_dice_0.9290.pth'
resume: /users/scratch/baryaacovi-2024-06-01/projects/MICCAI23-ProtoContra-SFDA/res/UNet_Abdomen_CT_Seg/exp_42_time_2024-05-06 07:53:15/saved_models/best_model_epoch_77_dice_0.9540.pth
continue_train: True
total_epochs: 102
random_seed: 999
organ_list:
- 'Spleen'
- 'R.Kidney'
- 'L.Kidney'
- 'Liver'

# Dataloader Setting
img_size:
- 256
- 256
batch_size: 16
num_workers: 8

# Model 
arch: 'UNet'
use_prototype: False
update_prototype: False
input_dim: 3
feat_dim: 32
output_dim: 64
num_classes: 5

# Optim parameters
lr: 0.001

# Loss parameters
ce_ignore_index: -1
dice_ignore_index: 0

# display
save_epochs: 10
eval_epochs: 1
display_steps: 100
save_visuals: True

# test
test: False