# Experiment Specific
experiment_name: 'UNet_Abdomen_CT_Seg'
data_root: '/users/scratch/baryaacovi-2024-06-01/projects/datasets/proto/prod'
save_root: '/users/scratch/baryaacovi-2024-06-01/projects/MICCAI23-ProtoContra-SFDA/res'
source_sites:
- 'MR'
eval_sites:
- 'MR'
resume_dir: ''
# resume: '/users/scratch/baryaacovi-2024-06-01/projects/MICCAI23-ProtoContra-SFDA/UNet_Abdomen_CT_Seg/exp_16_time_2024-05-01 11:28:57/saved_models/model_epoch_100_dice_1.0000.pth'
continue_train: False
total_epochs: 100
random_seed: 999
organ_list:
- 'Spleen'
- 'R.Kidney'
- 'L.Kidney'
- 'Liver'

# Dataloader Setting
img_size:
- 256
- 256
batch_size: 16
num_workers: 8

# Model 
arch: 'UNet'
use_prototype: False
update_prototype: False
input_dim: 3
feat_dim: 32
output_dim: 64
num_classes: 5

# Optim parameters
lr: 0.001

# Loss parameters
ce_ignore_index: -1
dice_ignore_index: 0

# display
save_epochs: 10
eval_epochs: 1
display_steps: 100
save_visuals: True

# test
test: False